export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ON_CHANGE_FORM_PRODUCT = "ON_CHANGE_FORM_PRODUCT";

export const RESET_FORM_PRODUCT = "RESET_FORM_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
